### PR TITLE
Wishlist page

### PR DESCRIPTION
**Pull request by foolhardy21**
This PR has:
- Wishlist page.

Feel free to review. Thanks.

### CODE REVIEW

**Review by aayushjain-code — COMMENTED** [review]
Try to decrease the size of each card as it looks too big...
Everything looks good bro..

**Review by ParthParolekar — APPROVED** [review]
Looks good to me!

**Review by anik31 — APPROVED** [review]
Everything looks good. Suggestion - instead of trash icon you can use cross icon as it will look better

**Comment by foolhardy21** [comment]
thanks @Aayushjain-code @anik31 @ParthParolekar . i have udpated the card size and replaced the trash icon with cross.

**Pull request merged**
